// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repoUser

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      string
	Email     string
	Username  string
	Password  string
	Profile   string
	SkillID   sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
