// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repoActivity

import (
	"time"
)

type Activity struct {
	ID           int64
	Title        string
	Description  string
	StartDate    time.Time
	EndDate      time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Participants string
	SkillID      int64
}
